repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Use ruff for all linting and formatting. It's faster than black.
    rev: v0.14.1
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

-   repo: https://github.com/gitleaks/gitleaks
    # Secret scanning to prevent committing sensitive data.
    rev: v8.28.0
    hooks:
    -   id: gitleaks
