repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: detect-private-key
    - id: mixed-line-ending
    - id: fix-byte-order-marker

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.3
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format


# (Optional) pre-push ANN gates — add only if you want local parity/latency guard
# - repo: local
#   hooks:
#     - id: ann-gates
#       name: ANN gates (DIAG≥0.99 · p95≤150ms)
#       language: system
#       stages: [push]
#       entry: python scripts/ann_verify_via_diag.py --help  # replace with the full gate as shared earlier
