"""Ephemeral test

Revision ID: ae2ab5a1b213
Revises:
Create Date: 2025-10-20 11:29:09.347534

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ae2ab5a1b213"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interaction_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("environment_hash", sa.Text(), nullable=False),
        sa.Column("causality_id", sa.UUID(), nullable=True),
        sa.Column("emitted_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action_type", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.BYTEA(), nullable=False),
        sa.Column("payload_hash", sa.Text(), nullable=False),
        sa.Column(
            "agent_support", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", "emitted_at_utc", name="pk_interaction_log"),
        sa.UniqueConstraint(
            "payload_hash", "emitted_at_utc", name="uq_payload_hash_emitted_at_utc"
        ),
        postgresql_partition_by="RANGE (emitted_at_utc)",
    )
    op.create_index(
        op.f("ix_interaction_log_agent_id"),
        "interaction_log",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_log_agent_support"),
        "interaction_log",
        ["agent_support"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_log_causality_id"),
        "interaction_log",
        ["causality_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_log_emitted_at_utc"),
        "interaction_log",
        ["emitted_at_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_log_environment_hash"),
        "interaction_log",
        ["environment_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_interaction_log_environment_hash"), table_name="interaction_log"
    )
    op.drop_index(
        op.f("ix_interaction_log_emitted_at_utc"), table_name="interaction_log"
    )
    op.drop_index(op.f("ix_interaction_log_causality_id"), table_name="interaction_log")
    op.drop_index(
        op.f("ix_interaction_log_agent_support"), table_name="interaction_log"
    )
    op.drop_index(op.f("ix_interaction_log_agent_id"), table_name="interaction_log")
    op.drop_table("interaction_log")
    # ### end Alembic commands ###
