name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
          pip install pytest

      - name: Run tests
        # This block securely loads the database URL from your GitHub repository's secrets.
        # It makes the DATABASE_URL available as an environment variable for the test run.
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python -m pytest
