name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'api/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r api/requirements.txt

      - name: Run tests with pytest
        # We must provide the environment variables our application needs to run.
        # We use GitHub's encrypted secrets for this.
        env:
          DATABASE_URL: "sqlite:///./test.db"
          NAOK_FULCRUM_PRIME_KEY: ${{ secrets.NAOK_FULCRUM_PRIME_KEY }}
          NAOK_FULCRUM_SALT: ${{ secrets.NAOK_FULCRUM_SALT }}
        run: python -m pytest
