name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    # This new "services" block starts a temporary PostgreSQL database
    # that runs alongside your tests.
    services:
      postgres:
        image: postgres:16-alpine
        # These credentials are only for this temporary test database
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        # This healthcheck ensures the tests don't start until the
        # database is fully ready to accept connections.
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        env:
          # IMPORTANT: We override the DATABASE_URL to connect to the
          # temporary service container, not "localhost".
          DATABASE_URL: "postgresql://testuser:testpassword@postgres:5432/testdb"
          # We still load the other secrets for your application logic
          NAOK_FULCRUM_PRIME_KEY: ${{ secrets.NAOK_FULCRUM_PRIME_KEY }}
          NAOK_FULCRUM_SALT: ${{ secrets.NAOK_FULCRUM_SALT }}
        run: python -m pytest
