# Fulcrum Continuous Integration Pipeline
# This workflow runs on every push and pull request to the main branch.
# It sets up the environment, installs dependencies, and runs the test suite.

name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Sets up the specified version of Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # Cache pip dependencies to speed up future builds
          cache: 'pip'
          cache-dependency-path: 'api/requirements.txt'

      # Step 3: Install all project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest httpx
          pip install -r api/requirements.txt

      # Step 4: Run the test suite
      # We run pytest from the project root to ensure all paths are correct.
      - name: Run tests with pytest
        run: python -m pytest
